server:
  port: 18091

spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:18858 #配置sentinel dashboard地址

feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
