spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18848

server:
  port: 18081

management:
  endpoints:
    web:
      exposure:
        include: "*"